LoadPackage( "LinearAlgebra" );

QQ := HomalgFieldOfRationals( );

CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1 := MatrixCategory( QQ );

func := function ( cat_1, homology_source_1, mor_list_1, homology_range_1 )
    return (
        (PreCompose)(
            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                rec(
                   ),
                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                (ObjectifyObjectForCAPWithAttributes)(
                    rec(
                       ),
                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                    Dimension,
                    (NumberRows)(
                        (SyzygiesOfRows)(
                            (SyzygiesOfColumns)(
                                (SyzygiesOfRows)(
                                      (UnderlyingMatrix)(
                                          mor_list_1[2]
                                      )
                                  ) * (SyzygiesOfColumns)(
                                      (UnderlyingMatrix)(
                                          mor_list_1[1]
                                      )
                                  )
                            )
                        )
                    )
                ),
                (ObjectifyObjectForCAPWithAttributes)(
                    rec(
                       ),
                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                    Dimension,
                    (NumberRows)(
                        (SyzygiesOfRows)(
                            (SyzygiesOfColumns)(
                                (SyzygiesOfRows)(
                                      (UnderlyingMatrix)(
                                          mor_list_1[2]
                                      )
                                  ) * (SyzygiesOfColumns)(
                                      (UnderlyingMatrix)(
                                          mor_list_1[1]
                                      )
                                  )
                            )
                        )
                    )
                ),
                UnderlyingMatrix,
                (HomalgIdentityMatrix)(
                    (NumberRows)(
                        (SyzygiesOfRows)(
                            (SyzygiesOfColumns)(
                                (SyzygiesOfRows)(
                                      (UnderlyingMatrix)(
                                          mor_list_1[2]
                                      )
                                  ) * (SyzygiesOfColumns)(
                                      (UnderlyingMatrix)(
                                          mor_list_1[1]
                                      )
                                  )
                            )
                        )
                    ),
                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_2
                )
            ),
            (PreCompose)(
                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                    rec(
                       ),
                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                    (Source)(
                        (PreCompose)(
                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                rec(
                                   ),
                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                (ObjectifyObjectForCAPWithAttributes)(
                                    rec(
                                       ),
                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                    Dimension,
                                    (NumberRows)(
                                        (SyzygiesOfRows)(
                                            (SyzygiesOfColumns)(
                                                (UnderlyingMatrix)(
                                                    (function ( cat_2, morphism_1_2, morphism_2_2 )
                                                        return (
                                                            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                                rec(
                                                                   ),
                                                                cat_2,
                                                                (Source)(
                                                                    morphism_1_2
                                                                ),
                                                                (Range)(
                                                                    morphism_2_2
                                                                ),
                                                                UnderlyingMatrix,
                                                                (UnderlyingMatrix)(
                                                                      morphism_1_2
                                                                  ) * (UnderlyingMatrix)(
                                                                      morphism_2_2
                                                                  )
                                                            )
                                                        );
                                                    end)(
                                                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                        (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                            rec(
                                                               ),
                                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                            (ObjectifyObjectForCAPWithAttributes)(
                                                                rec(
                                                                   ),
                                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                                Dimension,
                                                                (NumberRows)(
                                                                    (SyzygiesOfRows)(
                                                                        (UnderlyingMatrix)(
                                                                            mor_list_1[2]
                                                                        )
                                                                    )
                                                                )
                                                            ),
                                                            (Source)(
                                                                mor_list_1[2]
                                                            ),
                                                            UnderlyingMatrix,
                                                            (SyzygiesOfRows)(
                                                                (UnderlyingMatrix)(
                                                                    mor_list_1[2]
                                                                )
                                                            )
                                                        ),
                                                        (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                            rec(
                                                               ),
                                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                            (Range)(
                                                                mor_list_1[1]
                                                            ),
                                                            (ObjectifyObjectForCAPWithAttributes)(
                                                                rec(
                                                                   ),
                                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                                Dimension,
                                                                (NumberColumns)(
                                                                    (SyzygiesOfColumns)(
                                                                        (UnderlyingMatrix)(
                                                                            mor_list_1[1]
                                                                        )
                                                                    )
                                                                )
                                                            ),
                                                            UnderlyingMatrix,
                                                            (SyzygiesOfColumns)(
                                                                (UnderlyingMatrix)(
                                                                    mor_list_1[1]
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                ),
                                (Range)(
                                    (function ( cat_2, morphism_1_2, morphism_2_2 )
                                        return (
                                            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                rec(
                                                   ),
                                                cat_2,
                                                (Source)(
                                                    morphism_1_2
                                                ),
                                                (Range)(
                                                    morphism_2_2
                                                ),
                                                UnderlyingMatrix,
                                                (UnderlyingMatrix)(
                                                      morphism_1_2
                                                  ) * (UnderlyingMatrix)(
                                                      morphism_2_2
                                                  )
                                            )
                                        );
                                    end)(
                                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                        (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                            rec(
                                               ),
                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                            (ObjectifyObjectForCAPWithAttributes)(
                                                rec(
                                                   ),
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                Dimension,
                                                (NumberRows)(
                                                    (SyzygiesOfRows)(
                                                        (UnderlyingMatrix)(
                                                            mor_list_1[2]
                                                        )
                                                    )
                                                )
                                            ),
                                            (Source)(
                                                mor_list_1[2]
                                            ),
                                            UnderlyingMatrix,
                                            (SyzygiesOfRows)(
                                                (UnderlyingMatrix)(
                                                    mor_list_1[2]
                                                )
                                            )
                                        ),
                                        (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                            rec(
                                               ),
                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                            (Range)(
                                                mor_list_1[1]
                                            ),
                                            (ObjectifyObjectForCAPWithAttributes)(
                                                rec(
                                                   ),
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                Dimension,
                                                (NumberColumns)(
                                                    (SyzygiesOfColumns)(
                                                        (UnderlyingMatrix)(
                                                            mor_list_1[1]
                                                        )
                                                    )
                                                )
                                            ),
                                            UnderlyingMatrix,
                                            (SyzygiesOfColumns)(
                                                (UnderlyingMatrix)(
                                                    mor_list_1[1]
                                                )
                                            )
                                        )
                                    )
                                ),
                                UnderlyingMatrix,
                                (SyzygiesOfRows)(
                                    (SyzygiesOfColumns)(
                                        (UnderlyingMatrix)(
                                            (function ( cat_2, morphism_1_2, morphism_2_2 )
                                                return (
                                                    (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                        rec(
                                                           ),
                                                        cat_2,
                                                        (Source)(
                                                            morphism_1_2
                                                        ),
                                                        (Range)(
                                                            morphism_2_2
                                                        ),
                                                        UnderlyingMatrix,
                                                        (UnderlyingMatrix)(
                                                              morphism_1_2
                                                          ) * (UnderlyingMatrix)(
                                                              morphism_2_2
                                                          )
                                                    )
                                                );
                                            end)(
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                    rec(
                                                       ),
                                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                    (ObjectifyObjectForCAPWithAttributes)(
                                                        rec(
                                                           ),
                                                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                        Dimension,
                                                        (NumberRows)(
                                                            (SyzygiesOfRows)(
                                                                (UnderlyingMatrix)(
                                                                    mor_list_1[2]
                                                                )
                                                            )
                                                        )
                                                    ),
                                                    (Source)(
                                                        mor_list_1[2]
                                                    ),
                                                    UnderlyingMatrix,
                                                    (SyzygiesOfRows)(
                                                        (UnderlyingMatrix)(
                                                            mor_list_1[2]
                                                        )
                                                    )
                                                ),
                                                (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                    rec(
                                                       ),
                                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                    (Range)(
                                                        mor_list_1[1]
                                                    ),
                                                    (ObjectifyObjectForCAPWithAttributes)(
                                                        rec(
                                                           ),
                                                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                        Dimension,
                                                        (NumberColumns)(
                                                            (SyzygiesOfColumns)(
                                                                (UnderlyingMatrix)(
                                                                    mor_list_1[1]
                                                                )
                                                            )
                                                        )
                                                    ),
                                                    UnderlyingMatrix,
                                                    (SyzygiesOfColumns)(
                                                        (UnderlyingMatrix)(
                                                            mor_list_1[1]
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            ),
                            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                rec(
                                   ),
                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                (ObjectifyObjectForCAPWithAttributes)(
                                    rec(
                                       ),
                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                    Dimension,
                                    (NumberColumns)(
                                        (SyzygiesOfColumns)(
                                            (UnderlyingMatrix)(
                                                mor_list_1[1]
                                            )
                                        )
                                    )
                                ),
                                (Range)(
                                    (PreCompose)(
                                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                        mor_list_1[3],
                                        (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                            rec(
                                               ),
                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                            (Range)(
                                                mor_list_1[4]
                                            ),
                                            (ObjectifyObjectForCAPWithAttributes)(
                                                rec(
                                                   ),
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                Dimension,
                                                (NumberColumns)(
                                                    (SyzygiesOfColumns)(
                                                        (UnderlyingMatrix)(
                                                            mor_list_1[4]
                                                        )
                                                    )
                                                )
                                            ),
                                            UnderlyingMatrix,
                                            (SyzygiesOfColumns)(
                                                (UnderlyingMatrix)(
                                                    mor_list_1[4]
                                                )
                                            )
                                        )
                                    )
                                ),
                                UnderlyingMatrix,
                                (LeftDivide)(
                                    (SyzygiesOfColumns)(
                                        (UnderlyingMatrix)(
                                            mor_list_1[1]
                                        )
                                    ),
                                    (UnderlyingMatrix)(
                                        (PreCompose)(
                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                            mor_list_1[3],
                                            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                rec(
                                                   ),
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                (Range)(
                                                    mor_list_1[4]
                                                ),
                                                (ObjectifyObjectForCAPWithAttributes)(
                                                    rec(
                                                       ),
                                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                    Dimension,
                                                    (NumberColumns)(
                                                        (SyzygiesOfColumns)(
                                                            (UnderlyingMatrix)(
                                                                mor_list_1[4]
                                                            )
                                                        )
                                                    )
                                                ),
                                                UnderlyingMatrix,
                                                (SyzygiesOfColumns)(
                                                    (UnderlyingMatrix)(
                                                        mor_list_1[4]
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    ),
                    (ObjectifyObjectForCAPWithAttributes)(
                        rec(
                           ),
                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                        Dimension,
                        (NumberRows)(
                            (SyzygiesOfRows)(
                                (SyzygiesOfColumns)(
                                    (UnderlyingMatrix)(
                                        (PreCompose)(
                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                rec(
                                                   ),
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                (ObjectifyObjectForCAPWithAttributes)(
                                                    rec(
                                                       ),
                                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                    Dimension,
                                                    (NumberRows)(
                                                        (SyzygiesOfRows)(
                                                            (UnderlyingMatrix)(
                                                                mor_list_1[5]
                                                            )
                                                        )
                                                    )
                                                ),
                                                (Source)(
                                                    mor_list_1[5]
                                                ),
                                                UnderlyingMatrix,
                                                (SyzygiesOfRows)(
                                                    (UnderlyingMatrix)(
                                                        mor_list_1[5]
                                                    )
                                                )
                                            ),
                                            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                rec(
                                                   ),
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                (Range)(
                                                    mor_list_1[4]
                                                ),
                                                (ObjectifyObjectForCAPWithAttributes)(
                                                    rec(
                                                       ),
                                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                    Dimension,
                                                    (NumberColumns)(
                                                        (SyzygiesOfColumns)(
                                                            (UnderlyingMatrix)(
                                                                mor_list_1[4]
                                                            )
                                                        )
                                                    )
                                                ),
                                                UnderlyingMatrix,
                                                (SyzygiesOfColumns)(
                                                    (UnderlyingMatrix)(
                                                        mor_list_1[4]
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    ),
                    UnderlyingMatrix,
                    (RightDivide)(
                        (UnderlyingMatrix)(
                            (PreCompose)(
                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                    rec(
                                       ),
                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                    (ObjectifyObjectForCAPWithAttributes)(
                                        rec(
                                           ),
                                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                        Dimension,
                                        (NumberRows)(
                                            (SyzygiesOfRows)(
                                                (SyzygiesOfColumns)(
                                                    (UnderlyingMatrix)(
                                                        (PreCompose)(
                                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                                rec(
                                                                   ),
                                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                                (ObjectifyObjectForCAPWithAttributes)(
                                                                    rec(
                                                                       ),
                                                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                                    Dimension,
                                                                    (NumberRows)(
                                                                        (SyzygiesOfRows)(
                                                                            (UnderlyingMatrix)(
                                                                                mor_list_1[2]
                                                                            )
                                                                        )
                                                                    )
                                                                ),
                                                                (Source)(
                                                                    mor_list_1[2]
                                                                ),
                                                                UnderlyingMatrix,
                                                                (SyzygiesOfRows)(
                                                                    (UnderlyingMatrix)(
                                                                        mor_list_1[2]
                                                                    )
                                                                )
                                                            ),
                                                            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                                rec(
                                                                   ),
                                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                                (Range)(
                                                                    mor_list_1[1]
                                                                ),
                                                                (ObjectifyObjectForCAPWithAttributes)(
                                                                    rec(
                                                                       ),
                                                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                                    Dimension,
                                                                    (NumberColumns)(
                                                                        (SyzygiesOfColumns)(
                                                                            (UnderlyingMatrix)(
                                                                                mor_list_1[1]
                                                                            )
                                                                        )
                                                                    )
                                                                ),
                                                                UnderlyingMatrix,
                                                                (SyzygiesOfColumns)(
                                                                    (UnderlyingMatrix)(
                                                                        mor_list_1[1]
                                                                    )
                                                                )
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    ),
                                    (Range)(
                                        (PreCompose)(
                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                rec(
                                                   ),
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                (ObjectifyObjectForCAPWithAttributes)(
                                                    rec(
                                                       ),
                                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                    Dimension,
                                                    (NumberRows)(
                                                        (SyzygiesOfRows)(
                                                            (UnderlyingMatrix)(
                                                                mor_list_1[2]
                                                            )
                                                        )
                                                    )
                                                ),
                                                (Source)(
                                                    mor_list_1[2]
                                                ),
                                                UnderlyingMatrix,
                                                (SyzygiesOfRows)(
                                                    (UnderlyingMatrix)(
                                                        mor_list_1[2]
                                                    )
                                                )
                                            ),
                                            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                rec(
                                                   ),
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                (Range)(
                                                    mor_list_1[1]
                                                ),
                                                (ObjectifyObjectForCAPWithAttributes)(
                                                    rec(
                                                       ),
                                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                    Dimension,
                                                    (NumberColumns)(
                                                        (SyzygiesOfColumns)(
                                                            (UnderlyingMatrix)(
                                                                mor_list_1[1]
                                                            )
                                                        )
                                                    )
                                                ),
                                                UnderlyingMatrix,
                                                (SyzygiesOfColumns)(
                                                    (UnderlyingMatrix)(
                                                        mor_list_1[1]
                                                    )
                                                )
                                            )
                                        )
                                    ),
                                    UnderlyingMatrix,
                                    (SyzygiesOfRows)(
                                        (SyzygiesOfColumns)(
                                            (UnderlyingMatrix)(
                                                (PreCompose)(
                                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                    (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                        rec(
                                                           ),
                                                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                        (ObjectifyObjectForCAPWithAttributes)(
                                                            rec(
                                                               ),
                                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                            Dimension,
                                                            (NumberRows)(
                                                                (SyzygiesOfRows)(
                                                                    (UnderlyingMatrix)(
                                                                        mor_list_1[2]
                                                                    )
                                                                )
                                                            )
                                                        ),
                                                        (Source)(
                                                            mor_list_1[2]
                                                        ),
                                                        UnderlyingMatrix,
                                                        (SyzygiesOfRows)(
                                                            (UnderlyingMatrix)(
                                                                mor_list_1[2]
                                                            )
                                                        )
                                                    ),
                                                    (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                        rec(
                                                           ),
                                                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                        (Range)(
                                                            mor_list_1[1]
                                                        ),
                                                        (ObjectifyObjectForCAPWithAttributes)(
                                                            rec(
                                                               ),
                                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                            Dimension,
                                                            (NumberColumns)(
                                                                (SyzygiesOfColumns)(
                                                                    (UnderlyingMatrix)(
                                                                        mor_list_1[1]
                                                                    )
                                                                )
                                                            )
                                                        ),
                                                        UnderlyingMatrix,
                                                        (SyzygiesOfColumns)(
                                                            (UnderlyingMatrix)(
                                                                mor_list_1[1]
                                                            )
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                ),
                                (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                    rec(
                                       ),
                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                    (ObjectifyObjectForCAPWithAttributes)(
                                        rec(
                                           ),
                                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                        Dimension,
                                        (NumberColumns)(
                                            (SyzygiesOfColumns)(
                                                (UnderlyingMatrix)(
                                                    mor_list_1[1]
                                                )
                                            )
                                        )
                                    ),
                                    (Range)(
                                        (PreCompose)(
                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                            mor_list_1[3],
                                            (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                rec(
                                                   ),
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                (Range)(
                                                    mor_list_1[4]
                                                ),
                                                (ObjectifyObjectForCAPWithAttributes)(
                                                    rec(
                                                       ),
                                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                    Dimension,
                                                    (NumberColumns)(
                                                        (SyzygiesOfColumns)(
                                                            (UnderlyingMatrix)(
                                                                mor_list_1[4]
                                                            )
                                                        )
                                                    )
                                                ),
                                                UnderlyingMatrix,
                                                (SyzygiesOfColumns)(
                                                    (UnderlyingMatrix)(
                                                        mor_list_1[4]
                                                    )
                                                )
                                            )
                                        )
                                    ),
                                    UnderlyingMatrix,
                                    (LeftDivide)(
                                        (SyzygiesOfColumns)(
                                            (UnderlyingMatrix)(
                                                mor_list_1[1]
                                            )
                                        ),
                                        (UnderlyingMatrix)(
                                            (PreCompose)(
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                mor_list_1[3],
                                                (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                                    rec(
                                                       ),
                                                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                    (Range)(
                                                        mor_list_1[4]
                                                    ),
                                                    (ObjectifyObjectForCAPWithAttributes)(
                                                        rec(
                                                           ),
                                                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                        Dimension,
                                                        (NumberColumns)(
                                                            (SyzygiesOfColumns)(
                                                                (UnderlyingMatrix)(
                                                                    mor_list_1[4]
                                                                )
                                                            )
                                                        )
                                                    ),
                                                    UnderlyingMatrix,
                                                    (SyzygiesOfColumns)(
                                                        (UnderlyingMatrix)(
                                                            mor_list_1[4]
                                                        )
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        ),
                        (SyzygiesOfRows)(
                            (SyzygiesOfColumns)(
                                (UnderlyingMatrix)(
                                    (PreCompose)(
                                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                        (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                            rec(
                                               ),
                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                            (ObjectifyObjectForCAPWithAttributes)(
                                                rec(
                                                   ),
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                Dimension,
                                                (NumberRows)(
                                                    (SyzygiesOfRows)(
                                                        (UnderlyingMatrix)(
                                                            mor_list_1[5]
                                                        )
                                                    )
                                                )
                                            ),
                                            (Source)(
                                                mor_list_1[5]
                                            ),
                                            UnderlyingMatrix,
                                            (SyzygiesOfRows)(
                                                (UnderlyingMatrix)(
                                                    mor_list_1[5]
                                                )
                                            )
                                        ),
                                        (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                                            rec(
                                               ),
                                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                            (Range)(
                                                mor_list_1[4]
                                            ),
                                            (ObjectifyObjectForCAPWithAttributes)(
                                                rec(
                                                   ),
                                                CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                                                Dimension,
                                                (NumberColumns)(
                                                    (SyzygiesOfColumns)(
                                                        (UnderlyingMatrix)(
                                                            mor_list_1[4]
                                                        )
                                                    )
                                                )
                                            ),
                                            UnderlyingMatrix,
                                            (SyzygiesOfColumns)(
                                                (UnderlyingMatrix)(
                                                    mor_list_1[4]
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                ),
                (ObjectifyMorphismWithSourceAndRangeForCAPWithAttributes)(
                    rec(
                       ),
                    CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                    (ObjectifyObjectForCAPWithAttributes)(
                        rec(
                           ),
                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                        Dimension,
                        (NumberRows)(
                            (SyzygiesOfRows)(
                                (SyzygiesOfColumns)(
                                    (SyzygiesOfRows)(
                                          (UnderlyingMatrix)(
                                              mor_list_1[5]
                                          )
                                      ) * (SyzygiesOfColumns)(
                                          (UnderlyingMatrix)(
                                              mor_list_1[4]
                                          )
                                      )
                                )
                            )
                        )
                    ),
                    (ObjectifyObjectForCAPWithAttributes)(
                        rec(
                           ),
                        CAP_JIT_INTERNAL_GLOBAL_VARIABLE_1,
                        Dimension,
                        (NumberRows)(
                            (SyzygiesOfRows)(
                                (SyzygiesOfColumns)(
                                    (SyzygiesOfRows)(
                                          (UnderlyingMatrix)(
                                              mor_list_1[5]
                                          )
                                      ) * (SyzygiesOfColumns)(
                                          (UnderlyingMatrix)(
                                              mor_list_1[4]
                                          )
                                      )
                                )
                            )
                        )
                    ),
                    UnderlyingMatrix,
                    (RightDivide)(
                        (HomalgIdentityMatrix)(
                            (NumberRows)(
                                (SyzygiesOfRows)(
                                    (SyzygiesOfColumns)(
                                        (SyzygiesOfRows)(
                                              (UnderlyingMatrix)(
                                                  mor_list_1[5]
                                              )
                                          ) * (SyzygiesOfColumns)(
                                              (UnderlyingMatrix)(
                                                  mor_list_1[4]
                                              )
                                          )
                                    )
                                )
                            ),
                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_2
                        ),
                        (HomalgIdentityMatrix)(
                            (NumberRows)(
                                (SyzygiesOfRows)(
                                    (SyzygiesOfColumns)(
                                        (SyzygiesOfRows)(
                                              (UnderlyingMatrix)(
                                                  mor_list_1[5]
                                              )
                                          ) * (SyzygiesOfColumns)(
                                              (UnderlyingMatrix)(
                                                  mor_list_1[4]
                                              )
                                          )
                                    )
                                )
                            ),
                            CAP_JIT_INTERNAL_GLOBAL_VARIABLE_2
                        )
                    )
                )
            )
        )
    );
end;

compiled_func := CapJitCompiledFunction( func, [ ] );
